name: Sync Games to Alist

on:
  push:
    # 监听这两个分支的推送
    branches:
      - main
      - bao

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"
          rm: false
          strip_components: 0
          target: "/root/alist_data/games/${{ github.ref_name }}"
          exclude: |
            .git/